export const ASSET_STATUS = {
    OPERATIONAL: 'Operational',
    ISSUE_REPORTED: 'Issue Reported',
    UNDER_INSPECTION: 'Under Inspection',
    UNDER_MAINTENANCE: 'Under Maintenance',
    OUT_OF_SERVICE: 'Out of Service',
    RETIRED: 'Retired'
}

export const ALL_ASSET_STATUSES = Object.values(ASSET_STATUS)

// Transition map to check if transition from current to next status is valid
export const ASSET_STATUS_TRANSITIONS = {
    [ASSET_STATUS.OPERATIONAL]: [ASSET_STATUS.ISSUE_REPORTED, ASSET_STATUS.UNDER_INSPECTION, ASSET_STATUS.OUT_OF_SERVICE, ASSET_STATUS.RETIRED],
    [ASSET_STATUS.ISSUE_REPORTED]: [ASSET_STATUS.UNDER_INSPECTION, ASSET_STATUS.UNDER_MAINTENANCE, ASSET_STATUS.OUT_OF_SERVICE, ASSET_STATUS.RETIRED, ASSET_STATUS.OPERATIONAL],
    [ASSET_STATUS.UNDER_INSPECTION]: [ASSET_STATUS.UNDER_MAINTENANCE, ASSET_STATUS.OPERATIONAL, ASSET_STATUS.OUT_OF_SERVICE, ASSET_STATUS.RETIRED],
    [ASSET_STATUS.UNDER_MAINTENANCE]: [ASSET_STATUS.OPERATIONAL, ASSET_STATUS.UNDER_INSPECTION, ASSET_STATUS.OUT_OF_SERVICE, ASSET_STATUS.RETIRED],
    [ASSET_STATUS.OUT_OF_SERVICE]: [ASSET_STATUS.UNDER_INSPECTION, ASSET_STATUS.UNDER_MAINTENANCE, ASSET_STATUS.RETIRED, ASSET_STATUS.OPERATIONAL],
    [ASSET_STATUS.RETIRED]: [] // Retired is terminal, cannot transition out of retired
}

export function isValidAssetStatusTransition(current, next) {
    if (!current) return true; // Initial status creation
    if (current === next) return true

    const allowed = ASSET_STATUS_TRANSITIONS[current] || []

    return allowed.includes(next)
}
