export const ISSUE_STATUS = {
    REPORTED: 'Reported',
    ASSIGNED: 'Assigned',
    INSPECTION_STARTED: 'Inspection Started',
    MAINTENANCE_IN_PROGRESS: 'Maintenance In Progress',
    WAITING_FOR_PARTS: 'Waiting for Parts',
    RESOLVED: 'Resolved',
    CLOSED: 'Closed',
    REOPENED: 'Reopened',
}

export const ALL_ISSUE_STATUSES = Object.values(ISSUE_STATUS)

export const ISSUE_STATUS_TRANSITIONS = {
    [ISSUE_STATUS.REPORTED]: [ISSUE_STATUS.ASSIGNED, ISSUE_STATUS.INSPECTION_STARTED, ISSUE_STATUS.RETIRED, ISSUE_STATUS.RESOLVED],
    [ISSUE_STATUS.ASSIGNED]: [ISSUE_STATUS.INSPECTION_STARTED, ISSUE_STATUS.MAINTENANCE_IN_PROGRESS, ISSUE_STATUS.REPORTED, ISSUE_STATUS.RESOLVED],
    [ISSUE_STATUS.INSPECTION_STARTED]: [ISSUE_STATUS.MAINTENANCE_IN_PROGRESS, ISSUE_STATUS.WAITING_FOR_PARTS, ISSUE_STATUS.RESOLVED, ISSUE_STATUS.ASSIGNED],
    [ISSUE_STATUS.MAINTENANCE_IN_PROGRESS]: [ISSUE_STATUS.WAITING_FOR_PARTS, ISSUE_STATUS.RESOLVED, ISSUE_STATUS.INSPECTION_STARTED],
    [ISSUE_STATUS.WAITING_FOR_PARTS]: [ISSUE_STATUS.MAINTENANCE_IN_PROGRESS, ISSUE_STATUS.INSPECTION_STARTED, ISSUE_STATUS.RESOLVED],
    [ISSUE_STATUS.RESOLVED]: [ISSUE_STATUS.CLOSED, ISSUE_STATUS.REOPENED],
    [ISSUE_STATUS.CLOSED]: [ISSUE_STATUS.REOPENED], // Can reopen a closed issue
    [ISSUE_STATUS.REOPENED]: [ISSUE_STATUS.ASSIGNED, ISSUE_STATUS.INSPECTION_STARTED, ISSUE_STATUS.MAINTENANCE_IN_PROGRESS, ISSUE_STATUS.RESOLVED]
}

export function isValidIssueStatusTransition(current, next) {
    if (!current) return true
    if (current === next) return true

    const allowed = ISSUE_STATUS_TRANSITIONS[current] || []

    return allowed.includes(next)
}
